services:
  jenkins:
    image: myjenkins
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: controller_jenkins
    restart: always
    networks:
      - jenkins-network
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
  agent-python:
    image: python-agent
    hostname: agent-python
    privileged: true
    user: root
    container_name: agent-python
    ports:
      - "4444:22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=<Your Jenkins SSH Public Key>
    restart: always
    networks:
      - jenkins-network
  agent-java:
    image: java-agent
    hostname: agent-java
    privileged: true
    user: root
    container_name: agent-java
    ports:
      - "4445:22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=<Your Jenkins SSH Public Key>
    restart: always
    networks:
      - jenkins-network
volumes:
  jenkins-log:
    external: true
    name: jenkins-log
  jenkins-data:
    external: true
    name: jenkins-data
networks:
  jenkins-network: